[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio.workspace = true
futures.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true

axum = {version = "0.8.2", features = ["ws"]}
tower-http = { version = "0.6.1", features = ["trace"] }

