[workspace]
members = ["user_service"
]


[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
tower = { version = "0.4" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hyper = { version = "0.14" }
uuid = { version = "1.3", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }


