[workspace]
members = ["users"
]


[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
tower = { version = "0.5.1" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hyper = { version = "1.5.2" }
uuid = { version = "1.3", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
sqlx = { version = "0.8.2", features = ["sqlite", "runtime-tokio-native-tls"] }

